/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "/.src/**/*.{vue,js,ts,jsx,tsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ffb77d",
        "background": "#131313",
        "inverse-on-surface": "#313030",
        "surface-variant": "#353534",
        "on-secondary-fixed-variant": "#8f0044",
        "tertiary-container": "#00b5fc",
        "on-tertiary": "#00344c",
        "on-tertiary-fixed-variant": "#004c6c",
        "secondary-container": "#ff4a8d",
        "surface-container-highest": "#353534",
        "tertiary-fixed": "#c7e7ff",
        "on-primary-fixed-variant": "#6e3900",
        "on-secondary-container": "#590028",
        "on-surface-variant": "#ddc1ae",
        "surface-container-high": "#2a2a2a",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "secondary-fixed": "#ffd9e1",
        "on-primary-fixed": "#2f1500",
        "surface-container-lowest": "#0e0e0e",
        "primary": "#ffb77d",
        "on-primary": "#4d2600",
        "on-background": "#e5e2e1",
        "secondary-fixed-dim": "#ffb1c4",
        "inverse-primary": "#904d00",
        "on-secondary": "#65002e",
        "on-primary-container": "#623200",
        "surface-container-low": "#1c1b1b",
        "on-surface": "#e5e2e1",
        "primary-fixed-dim": "#ffb77d",
        "on-tertiary-fixed": "#001e2e",
        "outline-variant": "#564334",
        "surface-dim": "#131313",
        "on-secondary-fixed": "#3f001a",
        "outline": "#a48c7a",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#85cfff",
        "primary-container": "#ff8c00",
        "error": "#ffb4ab",
        "surface-bright": "#3a3939",
        "on-tertiary-container": "#004360",
        "inverse-surface": "#e5e2e1",
        "secondary": "#ffb1c4",
        "surface-container": "#201f1f",
        "surface": "#131313",
        "tertiary": "#85cfff",
        "primary-fixed": "#ffdcc3"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Space Grotesk"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
}
